com:
  example:
    properties:
      value: "application.yml value"

spring:
  profiles:
    group:
      default:
        - common
        - dev
      staging:
        - common
        - staging
      prod:
        - common
        - prod
